<a href="https://colab.research.google.com/github/inoorulameen2005-crypto/Data-Analytics-using-python-project/blob/main/ANOTHER%20DAY-1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**DAY-1**

**NUMPY**

In [ ]:
import numpy as np
students=np.array([
  [90,85],
  [78,92],
  [88,95]
])
print(students)

[[90 85]
 [78 92]
 [88 95]]


**ZERO**

In [ ]:
import numpy as np
arr=np.zeros((5,9))
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
